version: '3.8'
services:
  service1:
    image: zakgregory/animal-project-service1
    build:
      context: .
      dockerfile: Dockerfile1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  service2:
    image: zakgregory/animal-project-service2          
    build:
      context: .
      dockerfile: Dockerfile2
    ports:
    - target: 5001
      protocol: tcp

